language: java
script: mvn package -DskipTests
jdk: oraclejdk8
install: true
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - $HOME/.m2
