language: java
jdk: oraclejdk8
install: true
script:
  - mvn clean install
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - $HOME/.m2
services:
  - docker
before_install:
  - docker build -t jsie/webapp1 .
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
